name: voxalate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.10
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  http: ^0.13.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
