// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHQPQeR3F6z-tOgQIJUKc9tNudDPyfn8',
    appId: '1:193435076426:web:50406e4b972bb4a77863b3',
    messagingSenderId: '193435076426',
    projectId: 'voxalate',
    authDomain: 'voxalate.firebaseapp.com',
    storageBucket: 'voxalate.appspot.com',
    measurementId: 'G-VFQMT1ZXRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBEaQYB16ODykKVc65y4_lG8zbIdOOmQ',
    appId: '1:193435076426:android:280fc81bdf13c8c67863b3',
    messagingSenderId: '193435076426',
    projectId: 'voxalate',
    storageBucket: 'voxalate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpID6x-wtGYYTGqj-IyMEXG-nBLf7BXEQ',
    appId: '1:193435076426:ios:90dc95bb5e69b5f47863b3',
    messagingSenderId: '193435076426',
    projectId: 'voxalate',
    storageBucket: 'voxalate.appspot.com',
    iosClientId: '193435076426-4rjo5buf8vmt7uomfatri35ou43rhdr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxalate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpID6x-wtGYYTGqj-IyMEXG-nBLf7BXEQ',
    appId: '1:193435076426:ios:90dc95bb5e69b5f47863b3',
    messagingSenderId: '193435076426',
    projectId: 'voxalate',
    storageBucket: 'voxalate.appspot.com',
    iosClientId: '193435076426-4rjo5buf8vmt7uomfatri35ou43rhdr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxalate',
  );
}
